name: PR Workflow

on:
  pull_request:
    types: [opened, synchronize]
  pull_request_target:
    types: [closed]

jobs:
  handle-pr:
    runs-on: ubuntu-latest
    steps:
    - name: Call External API on PR Opened/Updated
      if: github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'synchronize')
      run: |
        PR_NUMBER=${{ github.event.pull_request.number }}
        response=$(curl --write-out "%{http_code}" --silent --output /dev/null -H "apiKey: eY3VfjsPDaOwhyY1VOzNmw==" "http://127.0.0.1:80/jobs/v1/ec61f8a9-a727-4613-b2c7-189350951f05/jobs/ci/$PR_NUMBER/run")
        echo "API Response Code: $response"
        if [ "$response" -ne 200 ]; then
          echo "::error::API check failed with response code $response"
          exit 1
    - name: Call External API on PR Merge
      if: github.event_name == 'pull_request_target' && github.event.action == 'closed' && github.event.pull_request.merged == true
      run: |
        PR_NUMBER=${{ github.event.pull_request.number }}
        curl --location --request DELETE "http://127.0.0.1:80/jobs/v1/ec61f8a9-a727-4613-b2c7-189350951f05/jobs/ci/$PR_NUMBER" --header "apiKey: eY3VfjsPDaOwhyY1VOzNmw=="
